import './assets/DataTables/jquery.dataTables.css'
import './assets/DataTables/Buttons-1.5.1/css/buttons.dataTables.css'
import './assets/DataTables/select-1.2.5/css/select.dataTables.min.css'
//import './assets/DataTables/AutoFill-2.2.2/css/autoFill.bootstrap.min.css'
import './assets/DataTables/Responsive-2.2.1/css/responsive.dataTables.min.css'
